### ISSUE TITLE
'errored' status from Heroku isn't handled

### ISSUE THREAD

**Issue by hunterchristian** [gregsadetsky/heroku-ci-badge#1]
Hi! First off, thank you for making this!

I've deployed the app to heroku, but the badge shows a question mark: https://draftr-heroku-ci-badge.herokuapp.com/last.svg

I looked into the application logs for the heroku-ci-badge app that I deployed, and saw the following:
```
[2019-06-16 00:03:36,329] ERROR in app: got unexpected build status: errored
```

I looked at `BADGES_ENUM` in `app.py`, and it seems that only 'succeeded' and 'failed' statuses are supported.

Would it be possible to support the 'errored' status as well?

Thanks!

**Comment by gregsadetsky** [comment]
Hey, glad to know that the code is proving useful to you, and yeah, that's a great idea! Thank you for the detailed feature request!

**Comment by gregsadetsky** [comment]
should be good to go! let me know if this works for you. cheers and thanks again!

**Comment by hunterchristian** [comment]
No problem, it works perfectly! Thanks for the quick turnaround!
